// Code Generated by Sidekick is for learning and experimentation purposes only.
// filename: src/components/cart/CartItemRow.jsx

import Button from "../common/Button";

// One row of the cart table. Quantity is clamped between 1 and available stock.
// onUpdate(cartItemId, productId, newQty) → calls PUT via the context.
// onRemove(cartItemId) → calls DELETE via the context.
const CartItemRow = ({ item, onUpdate, onRemove }) => {
  const decrease = () => {
    if (item.quantity > 1) onUpdate(item.id, item.product_id, item.quantity - 1);
  };

  const increase = () => {
    if (!item.stock || item.quantity < item.stock) {
      onUpdate(item.id, item.product_id, item.quantity + 1);
    }
  };

  return (
    <tr>
      <td>{item.name}</td>
      <td>₹{item.price.toFixed(2)}</td>
      <td>
        <button onClick={decrease} disabled={item.quantity <= 1}>−</button>
        <span className="qty-value">{item.quantity}</span>
        <button
          onClick={increase}
          disabled={item.stock ? item.quantity >= item.stock : false}
        >
          +
        </button>
      </td>
      <td>₹{(item.price * item.quantity).toFixed(2)}</td>
      <td>
        <Button variant="danger" onClick={() => onRemove(item.id)}>
          Remove
        </Button>
      </td>
    </tr>
  );
};

export default CartItemRow;
