// Code Generated by Sidekick is for learning and experimentation purposes only.
// filename: src/components/layout/Layout.jsx

import { Link, NavLink, useNavigate } from "react-router-dom";
import { useAuth } from "../../context/AuthContext";

// Shared page shell: Header (brand + nav + auth) and Footer wrap all pages.
const Layout = ({ children }) => {
  const { isAuthenticated, logout } = useAuth();
  const navigate = useNavigate();

  const handleLogout = () => {
    logout();
    navigate("/login", { replace: true });
  };

  const navClass = ({ isActive }) => (isActive ? "nav-link active" : "nav-link");

  return (
    <div className="app-shell">
      <header className="app-header">
        <div className="header-inner">
          <Link to="/products" className="brand">🛍️ ABC Shop</Link>

          <nav className="main-nav">
            <NavLink to="/products" className={navClass}>Products</NavLink>
            {isAuthenticated && <NavLink to="/cart" className={navClass}>Cart</NavLink>}
            {isAuthenticated && <NavLink to="/orders" className={navClass}>Orders</NavLink>}
          </nav>

          <div className="header-actions">
            {isAuthenticated ? (
              <button className="auth-btn" onClick={handleLogout}>Logout</button>
            ) : (
              <>
                <Link to="/login" className="auth-btn ghost">Login</Link>
                <Link to="/register" className="auth-btn">Register</Link>
              </>
            )}
          </div>
        </div>
      </header>

      <main className="app-main">{children}</main>

      <footer className="app-footer">
        <div className="footer-inner">
          <div className="footer-col">
            <h4>ABC Shop</h4>
            <p>Your one-stop online shopping app.</p>
          </div>
          <div className="footer-col">
            <h4>Shop</h4>
            <Link to="/products">Products</Link>
            <Link to="/cart">Cart</Link>
            <Link to="/orders">Orders</Link>
          </div>
          <div className="footer-col">
            <h4>Account</h4>
            <Link to="/login">Login</Link>
            <Link to="/register">Register</Link>
          </div>
        </div>
        <div className="footer-bottom">
          © {new Date().getFullYear()} ABC Organization. All rights reserved.
        </div>
      </footer>
    </div>
  );
};

export default Layout;
