// Code Generated by Sidekick is for learning and experimentation purposes only.
// filename: src/pages/OrderDetails.jsx

import { useEffect, useState } from "react";
import { useParams, useLocation, Link } from "react-router-dom";
import { getOrderById } from "../api/orderService";

const OrderDetails = () => {
  const { id } = useParams();
  const location = useLocation();
  const justPlaced = location.state?.justPlaced; // set right after checkout
  const [order, setOrder] = useState(null);
  const [error, setError] = useState("");

  useEffect(() => {
    getOrderById(id).then(setOrder).catch((err) => setError(err.message));
  }, [id]);

  if (error) return <p className="error-text">{error}</p>;
  if (!order) return <p>Loading order...</p>;

  return (
    <section className="order-details">
      {justPlaced && <p className="success-text">✓ Order placed successfully!</p>}

      <h2>Order #{order.id}</h2>
      <p>Status: {order.status}</p>
      <p>Date: {new Date(order.created_at).toLocaleString()}</p>

      <table>
        <thead>
          <tr><th>Product</th><th>Quantity</th><th>Unit Price</th><th>Subtotal</th></tr>
        </thead>
        <tbody>
          {order.items.map((item) => (
            <tr key={item.id}>
              <td>{item.product?.name}</td>
              <td>{item.quantity}</td>
              <td>₹{parseFloat(item.unit_price).toFixed(2)}</td>
              <td>₹{(parseFloat(item.unit_price) * item.quantity).toFixed(2)}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <p className="order-total">Total: ₹{parseFloat(order.total_amount).toFixed(2)}</p>
      <Link to="/orders">← Back to Order History</Link>
    </section>
  );
};

export default OrderDetails;
