// Code Generated by Sidekick is for learning and experimentation purposes only.
// filename: src/api/cartService.js

import axiosClient from "./axiosClient";

// GET /carts/items — list the logged-in user's cart items.
export const getCart = () =>
  axiosClient.get("/carts/items").then((res) => res.data);

// POST /carts/items — add a product (body per backend contract).
export const addToCart = (productId, quantity) =>
  axiosClient
    .post("/carts/items", { product_id: productId, quantity })
    .then((res) => res.data);

// PUT /carts/items/{cart_item_id} — update the quantity of an existing line.
export const updateCartItem = (cartItemId, quantity) =>
  axiosClient
    .put(`/carts/items/${cartItemId}`, { quantity })
    .then((res) => res.data);

// DELETE /carts/items/{cart_item_id} — remove a single cart line by its id.
export const removeFromCart = (cartItemId) =>
  axiosClient.delete(`/carts/items/${cartItemId}`).then((res) => res.data);
