// Code Generated by Sidekick is for learning and experimentation purposes only.
// filename: src/api/productService.js

import axiosClient from "./axiosClient";

// GET /products — full catalogue (filtered client-side for search).
export const getProducts = () =>
  axiosClient.get("/products").then((res) => res.data);

// GET /products/{product_id} — detailed info for one product.
export const getProductById = (productId) =>
  axiosClient.get(`/products/${productId}`).then((res) => res.data);

// GET /products/categories/{category_id} — resolve a category id to its name.
export const getCategoryById = (categoryId) =>
  axiosClient.get(`/products/categories/${categoryId}`).then((res) => res.data);
